/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/uiDemo/list/BagList.lh
 */
export class BagListRTBase extends Laya.Box {
    public bagList!: Laya.List;
    public tips!: Laya.Image;
    public itemImg!: Laya.Image;
    public itemNumber!: Laya.Label;
    public itemReadme!: Laya.TextArea;
}

