/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Loading.ls
 */
export class MainBase extends Laya.Scene {
    public loadingBar!: Laya.ProgressBar;
}

